[build-system]
requires = ["setuptools >= 61.0.0"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">= 3.10"
version = "0.0.1"
dynamic = []
name = "HousingAnalysis"
authors = [
  {name = "RBC"}
]
maintainers = [
  {name = "RBC"}
]
description = "Housing Analysis repo"
readme = "README.md"
license = {text = "MIT License"}
keywords = ["housing", "machine learning", "statistics", "economics"]

dependecies = [
    "pandas>=2.0.0",
    "numpy>=2.0.0",
    "matplotlib>=3.0.0",
    "seaborn>=0.13.0",
    "scikit-learn>=1.5.0",
    "scipy>= 1.14.0",
    "dash >= 2.18.0",
    "pyod >= 2.0.0",
    "fredapi >= 0.5.0",
    "yfinance >= 0.2.50",
    "statsmodels >= 0.14.0",
    "QuantLib >= 1.30",
    "prophet >= 1.1.6",
    "darts >= 0.31.0",
    "pycaret >= 3.3.2"
    
    
    
]

classifiers = [
  # How marure is this project? Common values are
  #  1 - Planning
  #  2 - Pre-Alpha
  #  3 - Alpha
  #  4 - Beta
  #  5 - Production / Stable
  #  6 - Mature
  #  7 - Inactive
  "Development Status :: 1 - Planning", 
  "Intended Audience: Economists, Quantitative Analysts, Housing Sector Analysts",
  "Topic :: Quantitative Analysis of the Housing Sector",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

[project.urls]
Homepage = "https://github.com/rboletcafaro/HousingAnalysis"
Repository = "https://github.com/rboletcafaro/HousingAnalysis"
Dashboard = ""

